-- =========================
-- 1. DROP TABLES IF EXIST
-- =========================
DROP TABLE IF EXISTS site_inventory;
DROP TABLE IF EXISTS regions;

select * from site_inventory;
SELECT * FROM regions;
-- =========================
-- 2. CREATE REGIONS TABLE
-- =========================
CREATE TABLE regions (
    id SERIAL PRIMARY KEY,
    lot_number INTEGER UNIQUE NOT NULL,
    region_name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO regions (lot_number, region_name)
VALUES
(1,'BENGUET'),
(2,'IFUGAO'),
(3,'KALINGA'),
(4,'PANGASINAN'),
(5,'QUEZON'),
(6,'ILOCOS')
ON CONFLICT DO NOTHING;

-- =========================
-- 3. CREATE SITE INVENTORY
-- =========================
CREATE TABLE site_inventory (
    id SERIAL PRIMARY KEY,
    region_name VARCHAR(100) REFERENCES regions(region_name) ON DELETE CASCADE,
    "NO." TEXT,
    "SITENAME" TEXT,
    "PROVINCE" TEXT,
    "MUNICIPALITY" TEXT,
    "REGION" TEXT,  -- after MUNICIPALITY
    "PHASE 1 ORIGINAL AIRMAC" TEXT,
    "SPARE MODEM USED" TEXT,
    "SPARE MODEM USED " TEXT, -- only PANGASINAN
    "PHASE 2 AIRMAC" TEXT,
    "PHASE 1 GRAFANA AIMAC" TEXT,
    "PHASE 1 IP ADDRESS" TEXT,
    "PHASE 2 IP ADDRESS" TEXT,
    "PHASE 1 SERIAL" TEXT,
    "PHASE 1 TRANCEIVER" TEXT,
    "PHASE 1 EAP225-outdoor s/n 1" TEXT,
    "PHASE 1 EAP225-outdoor s/n 2" TEXT,
    "PHASE 1 ER-605 SERIAL" TEXT,
    "PHASE 1 LAT" TEXT,
    "PHASE 1 LONG" TEXT,
    "PHASE 1 TRANCEIVER MODEL" TEXT,
    "PHASE 1 MODEM MODEL" TEXT,
    "PHASE 2 EAP225-outdoor s/n 1" TEXT,
    "PHASE 2 ASSIGNED KAD" TEXT,
    "INSTALLATION DATE" TEXT,
    "UAT SPEEDTEST MIR DL" TEXT,
    "UAT SPEEDTEST MIR UL" TEXT,
    "LATENCY" TEXT,
    "UAT SPEEDTEST CIR AP1 DL" TEXT,
    "UAT SPEEDTEST CIR AP1 UL" TEXT,
    "AP1 LATENCY" TEXT,
    "UAT SPEEDTEST CIR AP2 DL" TEXT,
    "UAT SPEEDTEST CIR AP2 UL" TEXT,
    "AP2 LATENCY" TEXT,
    "UAT TEST DATE (DICT INPUT)" TEXT,
    "LAT" TEXT,
    "LONG" TEXT,
    "2 - 3 SITE CONTACTS" TEXT,
    "OLD EAP225" TEXT,
    "SITE CONTACT EMAIL/SOCMED" TEXT,
    "REMARKS" TEXT
);

-- =========================
-- 4. CREATE INDEX
-- =========================
CREATE INDEX idx_inventory_region ON site_inventory(region_name);

-- =========================
-- 5. IMPORT CSV FILES
-- =========================

-- BENGUET
COPY site_inventory(
    "NO.", "SITENAME", "PROVINCE", "MUNICIPALITY", "REGION",
    "PHASE 1 ORIGINAL AIRMAC", "SPARE MODEM USED", "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC", "PHASE 1 IP ADDRESS", "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL", "PHASE 1 TRANCEIVER", "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2", "PHASE 1 ER-605 SERIAL", "PHASE 1 LAT",
    "PHASE 1 LONG", "PHASE 1 TRANCEIVER MODEL", "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1", "PHASE 2 ASSIGNED KAD", "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL", "UAT SPEEDTEST MIR UL", "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL", "UAT SPEEDTEST CIR AP1 UL", "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL", "UAT SPEEDTEST CIR AP2 UL", "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)", "LAT", "LONG", "2 - 3 SITE CONTACTS",
    "OLD EAP225", "SITE CONTACT EMAIL/SOCMED", "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_BENGUET.csv' DELIMITER ',' CSV HEADER;

-- Set region_name using the PROVINCE column
UPDATE site_inventory
SET region_name = 'BENGUET'
WHERE "PROVINCE" = 'BENGUET';

-- IFUGAO
COPY site_inventory(
  "NO.",
    "SITENAME",
    "PROVINCE",
    "MUNICIPALITY",
    "REGION",
    "PHASE 1 ORIGINAL AIRMAC",
    "SPARE MODEM USED",
    "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC",
    "PHASE 1 IP ADDRESS",
    "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL",
    "PHASE 1 TRANCEIVER",
    "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2",
    "PHASE 1 ER-605 SERIAL",
    "PHASE 1 LAT",
    "PHASE 1 LONG",
    "PHASE 1 TRANCEIVER MODEL",
    "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1",
    "PHASE 2 ASSIGNED KAD",
    "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL",
    "UAT SPEEDTEST MIR UL",
    "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL",
    "UAT SPEEDTEST CIR AP1 UL",
    "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL",
    "UAT SPEEDTEST CIR AP2 UL",
    "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)",
    "LAT",
    "LONG",
    "2 - 3 SITE CONTACTS",
    "OLD EAP225",
    "SITE CONTACT EMAIL/SOCMED",
    "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_ IFUGAO.csv' DELIMITER ',' CSV HEADER;

UPDATE site_inventory SET region_name = 'IFUGAO' WHERE "PROVINCE" = 'Ifugao';

-- KALINGA
COPY site_inventory(
    "NO.", "SITENAME","PROVINCE","MUNICIPALITY", "REGION",
    "PHASE 1 ORIGINAL AIRMAC", "SPARE MODEM USED", "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC", "PHASE 1 IP ADDRESS", "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL", "PHASE 1 TRANCEIVER", "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2", "PHASE 1 ER-605 SERIAL", "PHASE 1 LAT",
    "PHASE 1 LONG", "PHASE 1 TRANCEIVER MODEL", "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1", "PHASE 2 ASSIGNED KAD", "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL", "UAT SPEEDTEST MIR UL", "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL", "UAT SPEEDTEST CIR AP1 UL", "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL", "UAT SPEEDTEST CIR AP2 UL", "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)", "LAT", "LONG", "2 - 3 SITE CONTACTS",
    "OLD EAP225", "SITE CONTACT EMAIL/SOCMED", "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_ KALINGA.csv' DELIMITER ',' CSV HEADER;

UPDATE site_inventory SET region_name = 'KALINGA' WHERE "PROVINCE" = 'Kalinga';

-- PANGASINAN (with SPARE MODEM USED 2)
COPY site_inventory(
    "NO.", "SITENAME", "PROVINCE", "MUNICIPALITY", "REGION",
    "PHASE 1 ORIGINAL AIRMAC", "SPARE MODEM USED", "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC", "PHASE 1 IP ADDRESS", "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL", "PHASE 1 TRANCEIVER", "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2", "PHASE 1 ER-605 SERIAL", "PHASE 1 LAT",
    "PHASE 1 LONG", "PHASE 1 TRANCEIVER MODEL", "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1", "PHASE 2 ASSIGNED KAD","SPARE MODEM USED ", "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL", "UAT SPEEDTEST MIR UL", "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL", "UAT SPEEDTEST CIR AP1 UL", "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL", "UAT SPEEDTEST CIR AP2 UL", "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)", "LAT", "LONG", "2 - 3 SITE CONTACTS",
    "OLD EAP225", "SITE CONTACT EMAIL/SOCMED", "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_PANGASINAN.csv' DELIMITER ',' CSV HEADER;

UPDATE site_inventory SET region_name = 'PANGASINAN' WHERE "PROVINCE" = 'PANGASINAN';

-- QUEZON
COPY site_inventory(
    "NO.", "SITENAME", "PROVINCE", "MUNICIPALITY", "REGION",
    "PHASE 1 ORIGINAL AIRMAC", "SPARE MODEM USED", "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC", "PHASE 1 IP ADDRESS", "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL", "PHASE 1 TRANCEIVER", "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2", "PHASE 1 ER-605 SERIAL", "PHASE 1 LAT",
    "PHASE 1 LONG", "PHASE 1 TRANCEIVER MODEL", "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1", "PHASE 2 ASSIGNED KAD", "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL", "UAT SPEEDTEST MIR UL", "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL", "UAT SPEEDTEST CIR AP1 UL", "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL", "UAT SPEEDTEST CIR AP2 UL", "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)", "LAT", "LONG", "2 - 3 SITE CONTACTS",
    "OLD EAP225", "SITE CONTACT EMAIL/SOCMED", "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_QUEZON.csv' DELIMITER ',' CSV HEADER;

UPDATE site_inventory SET region_name = 'QUEZON' WHERE "PROVINCE" = 'QUEZON';

-- ILOCOS
COPY site_inventory(
    "NO.", "SITENAME", "PROVINCE", "MUNICIPALITY", "REGION",
    "PHASE 1 ORIGINAL AIRMAC", "SPARE MODEM USED", "PHASE 2 AIRMAC",
    "PHASE 1 GRAFANA AIMAC", "PHASE 1 IP ADDRESS", "PHASE 2 IP ADDRESS",
    "PHASE 1 SERIAL", "PHASE 1 TRANCEIVER", "PHASE 1 EAP225-outdoor s/n 1",
    "PHASE 1 EAP225-outdoor s/n 2", "PHASE 1 ER-605 SERIAL", "PHASE 1 LAT",
    "PHASE 1 LONG", "PHASE 1 TRANCEIVER MODEL", "PHASE 1 MODEM MODEL",
    "PHASE 2 EAP225-outdoor s/n 1", "PHASE 2 ASSIGNED KAD", "INSTALLATION DATE",
    "UAT SPEEDTEST MIR DL", "UAT SPEEDTEST MIR UL", "LATENCY",
    "UAT SPEEDTEST CIR AP1 DL", "UAT SPEEDTEST CIR AP1 UL", "AP1 LATENCY",
    "UAT SPEEDTEST CIR AP2 DL", "UAT SPEEDTEST CIR AP2 UL", "AP2 LATENCY",
    "UAT TEST DATE (DICT INPUT)", "LAT", "LONG", "2 - 3 SITE CONTACTS",
    "OLD EAP225", "SITE CONTACT EMAIL/SOCMED", "REMARKS"
)
FROM 'C:\temp\STATUS_438_VSAT_GIDA_PHASE_2_ILOCOS.csv' DELIMITER ',' CSV HEADER;

UPDATE site_inventory SET region_name = 'ILOCOS' WHERE "PROVINCE" = 'ILOCOS NORTE';

-- =========================
-- 6. VERIFY DATA
-- =========================
-- View all regions with sites
SELECT r.region_name, s."SITENAME"
FROM regions r
LEFT JOIN site_inventory s
ON r.region_name = s.region_name
ORDER BY r.region_name;

-- Count sites per region
SELECT region_name, COUNT(*) AS total_sites
FROM site_inventory
GROUP BY region_name
ORDER BY region_name;